import { existsSync, readFileSync, writeFileSync } from "node:fs";
import * as p from "@clack/prompts";
import { ConsumerIndexSchema, type ConsumerIndex } from "../shared/index.js";
import pc from "picocolors";
import { ApiError, createConsumer, fetchDocs, whoami } from "../lib/api.js";
import { ensureBruceDirs, mergeCredentials } from "../lib/credentials.js";
import { consumersIndexPath, docsPath } from "../lib/paths.js";
import { readProducerManifest } from "../lib/producerManifest.js";
import { inferProducerName } from "../lib/slug.js";

export interface ConsumerAddOptions {
  /** Manual path — a pre-existing token pasted from the producer's dashboard. */
  url?: string;
  token?: string;
  /**
   * Auto-discovery path (DESIGN_NOTES.md §17): resolves a producer by slug
   * under the same owner as the agent key and mints the relationship
   * directly, instead of requiring a token generated by hand beforehand.
   */
  agentKey?: string;
  producerSlug?: string;
  bruceUrl?: string;
  name?: string;
}

export async function consumerAddCommand(options: ConsumerAddOptions): Promise<void> {
  p.intro(pc.bold("bruce consumer add"));
  const spinner = p.spinner();

  let bruceApiUrl: string;
  let token: string;
  let consumerId: string;
  let producerSlug: string;
  let producerId: string;
  let producerName: string;

  if (options.agentKey) {
    if (!options.producerSlug || !options.bruceUrl) {
      p.log.error("--agent-key requires --producer-slug and --bruce-url.");
      process.exitCode = 1;
      return;
    }
    spinner.start(`Linking as a consumer of "${options.producerSlug}"`);
    try {
      // If this repo is ALSO a registered producer (bruce/producer.json — e.g. a backend that
      // both exposes its own API and calls a third-party one), tell the server so the graph can
      // connect this consumer entry to the real producer node instead of rendering it as an
      // unlinked name that happens to match — same fix as the same-repo DB connection case.
      const ownManifest = readProducerManifest();
      const created = await createConsumer(options.bruceUrl, options.agentKey, options.producerSlug, options.name ?? inferProducerName(), {
        kind: "api",
        linkedProducerId: ownManifest?.producerId,
      });
      bruceApiUrl = created.bruceApiUrl;
      token = created.token;
      consumerId = created.consumerId;
      producerSlug = created.producerSlug;
    } catch (err) {
      spinner.stop("Failed", 1);
      p.log.error(String(err));
      if (err instanceof ApiError && err.status === 404) {
        // The single most common cause: --producer-slug was guessed instead of looked up — an
        // agent_key can't read anything it didn't just create, so a wrong guess 404s exactly
        // like a producer that doesn't exist. `producers list` is the fix either way: confirms
        // the guess, or surfaces the real slug (including ones registered in a different
        // session/workspace this one never saw).
        p.log.message(
          `Tip: run \`bruce producers list --agent-key ${options.agentKey} --bruce-url ${options.bruceUrl}\` to see every producer actually registered under this account (not just ones from this session) instead of guessing a slug.`,
        );
      }
      process.exitCode = 1;
      return;
    }
    // The by-slug endpoint doesn't echo the producer's numeric id or display name (agent_key
    // can't read producer details beyond the slug it already asked for) — whoami on the
    // freshly-minted consumer token resolves both from the token itself, no extra trust needed.
    const identity = await whoami(bruceApiUrl, token);
    if (identity.kind !== "consumer_key") throw new Error("unreachable");
    producerId = identity.producerId;
    producerName = identity.producerName;
    spinner.stop(`Registered as a consumer of "${producerName}" (${producerSlug})`);
  } else {
    if (!options.url || !options.token) {
      p.log.error("Provide either --url and --token, or --agent-key with --producer-slug and --bruce-url.");
      process.exitCode = 1;
      return;
    }
    spinner.start("Identifying producer from token");
    const identity = await whoami(options.url, options.token);
    if (identity.kind !== "consumer_key") {
      spinner.stop("Failed");
      p.log.error("That token is not a consumer key. Ask the API owner for a consumer relationship token.");
      process.exitCode = 1;
      return;
    }
    bruceApiUrl = options.url;
    token = options.token;
    consumerId = identity.consumerId;
    producerSlug = identity.producerSlug;
    producerId = identity.producerId;
    producerName = identity.producerName;
    spinner.stop(`Registered as a consumer of "${producerName}" (${producerSlug})`);
  }

  mergeCredentials({
    consumers: {
      [producerSlug]: { token, bruceApiUrl, consumerId, producerId, producerName },
    },
  });

  ensureBruceDirs();
  const indexFile = consumersIndexPath();
  const current: ConsumerIndex = existsSync(indexFile)
    ? ConsumerIndexSchema.parse(JSON.parse(readFileSync(indexFile, "utf-8")))
    : { relationships: [] };
  if (!current.relationships.some((r) => r.producerSlug === producerSlug)) {
    current.relationships.push({
      producerSlug,
      producerName,
      bruceApiUrl,
      mappingFile: `bruce/consumers/${producerSlug}-map.json`,
    });
  }
  writeFileSync(indexFile, JSON.stringify(current, null, 2));

  // Best-effort, not fatal: the consumer relationship above is already real and saved by this
  // point, and docs are only fetchable once the producer has published at least one snapshot —
  // true for a properly-sequenced auto-discovery run (DESIGN_NOTES.md §20), but not guaranteed
  // in general (a manually-shared token for a not-yet-published producer, a transient network
  // blip). Failing the whole command here would throw away a link that already succeeded over a
  // step that's genuinely optional — `bruce init` re-fetches missing docs on its own (below).
  spinner.start("Downloading API docs");
  try {
    const markdown = await fetchDocs(bruceApiUrl, token, producerId);
    writeFileSync(docsPath(producerSlug), markdown);
    spinner.stop(`Docs saved to bruce/docs/${producerSlug}-api-doc.md`);
  } catch (err) {
    spinner.stop(`No docs yet (${err instanceof ApiError ? err.message : String(err)}) — consumer link still saved, docs will download the next time \`bruce init\` runs.`);
  }

  p.outro(`Run ${pc.cyan("bruce init")} (or ${pc.cyan("bruce scan")}) to map how this repo uses "${producerName}".`);
}
