import { z } from "zod";

export const CriticalitySchema = z.enum(["low", "medium", "high", "critical"]);
export type Criticality = z.infer<typeof CriticalitySchema>;

export const HttpMethodSchema = z.enum(["GET", "POST", "PUT", "PATCH", "DELETE"]);
export type HttpMethod = z.infer<typeof HttpMethodSchema>;

/**
 * bruce/consumers/<producer-slug>-map.json
 * Generated by `bruce init` / patched by `bruce scan` in a project's consumer role.
 */
export const ConsumerFieldUsageSchema = z.object({
  importance: CriticalitySchema,
  usedIn: z.array(z.string()),
});

export const ConsumerEndpointUsageSchema = z.object({
  method: HttpMethodSchema,
  path: z.string(),
  purpose: z.string(),
  criticality: CriticalitySchema,
  fields: z.record(z.string(), ConsumerFieldUsageSchema),
  errorHandling: z.record(z.string(), z.enum(["handled", "missing"])).optional(),
});

export const ConsumerMappingSchema = z.object({
  producer: z.string(),
  generatedAt: z.string(),
  endpoints: z.array(ConsumerEndpointUsageSchema),
});
export type ConsumerMapping = z.infer<typeof ConsumerMappingSchema>;

/**
 * bruce/publisher.json
 * Generated by `bruce init` / patched by `bruce scan` in a project's publisher role.
 * This is the contract snapshot pushed via `bruce publish`.
 */
export const PublisherFieldSchema = z.object({
  type: z.string(),
  criticality: CriticalitySchema.optional(),
  /** Names of prior fields this one supersedes — lets the diff engine tell a rename/restructure from a plain removal. */
  replaces: z.array(z.string()).optional(),
});

export const PublisherEndpointSchema = z.object({
  method: HttpMethodSchema,
  path: z.string(),
  description: z.string().optional(),
  responseFields: z.record(z.string(), PublisherFieldSchema),
});

export const PublisherSnapshotSchema = z.object({
  producer: z.string(),
  generatedAt: z.string(),
  endpoints: z.array(PublisherEndpointSchema),
  /** Human-readable API docs, folded in here rather than a separate table/endpoint. */
  docsMarkdown: z.string().optional(),
});
export type PublisherSnapshot = z.infer<typeof PublisherSnapshotSchema>;

/**
 * Change Intelligence Object — server-computed diff output, per DESIGN_NOTES.md §5.
 */
export const ChangeKindSchema = z.enum([
  "field_removed",
  "field_renamed",
  "field_restructured",
  "field_added",
  "endpoint_removed",
  "endpoint_added",
]);

export const ChangeIntelligenceObjectSchema = z.object({
  type: z.enum(["breaking_change", "non_breaking_change"]),
  service: z.string(),
  endpoint: z.string(),
  change: z.object({
    kind: ChangeKindSchema,
    field: z.string(),
    replacement: z.string().optional(),
  }),
  severity: z.enum(["low", "medium", "high"]),
  affectedConsumers: z.array(z.string()),
  migration: z.object({
    required: z.boolean(),
    notes: z.string().optional(),
  }),
});
export type ChangeIntelligenceObject = z.infer<typeof ChangeIntelligenceObjectSchema>;

/**
 * JWT claim shapes for the three token kinds sharing one auth middleware
 * (owner dashboard session, producer publish key, consumer relationship key).
 */
export const OwnerSessionClaimsSchema = z.object({
  kind: z.literal("owner_session"),
  ownerId: z.string(),
  jti: z.string(),
});

export const ProducerKeyClaimsSchema = z.object({
  kind: z.literal("producer_key"),
  producerId: z.string(),
  jti: z.string(),
});

export const ConsumerKeyClaimsSchema = z.object({
  kind: z.literal("consumer_key"),
  consumerId: z.string(),
  producerId: z.string(),
  jti: z.string(),
});

export const JwtClaimsSchema = z.discriminatedUnion("kind", [
  OwnerSessionClaimsSchema,
  ProducerKeyClaimsSchema,
  ConsumerKeyClaimsSchema,
]);
export type JwtClaims = z.infer<typeof JwtClaimsSchema>;
export type OwnerSessionClaims = z.infer<typeof OwnerSessionClaimsSchema>;
export type ProducerKeyClaims = z.infer<typeof ProducerKeyClaimsSchema>;
export type ConsumerKeyClaims = z.infer<typeof ConsumerKeyClaimsSchema>;

/**
 * bruce/consumers/index.json — manifest of registered consumer relationships.
 */
export const ConsumerRelationshipSchema = z.object({
  producerSlug: z.string(),
  producerName: z.string(),
  bruceApiUrl: z.string(),
  mappingFile: z.string(),
});

export const ConsumerIndexSchema = z.object({
  relationships: z.array(ConsumerRelationshipSchema),
});
export type ConsumerIndex = z.infer<typeof ConsumerIndexSchema>;

/**
 * .bruce/state.json — scan checkpoints, one entry per role.
 */
export const ScanStateSchema = z.object({
  lastScannedCommit: z.string().nullable(),
  lastFullScanCommit: z.string().nullable(),
  trackedFiles: z.array(z.string()),
  mappingHash: z.string().nullable(),
});
export type ScanState = z.infer<typeof ScanStateSchema>;

export const BruceStateSchema = z.object({
  producer: ScanStateSchema.optional(),
  consumers: z.record(z.string(), ScanStateSchema).optional(),
});
export type BruceState = z.infer<typeof BruceStateSchema>;
