import { z } from "zod";

export const CriticalitySchema = z.enum(["low", "medium", "high", "critical"]);
export type Criticality = z.infer<typeof CriticalitySchema>;

export const HttpMethodSchema = z.enum(["GET", "POST", "PUT", "PATCH", "DELETE"]);
export type HttpMethod = z.infer<typeof HttpMethodSchema>;

/**
 * bruce/consumers/<producer-slug>-map.json
 * Generated by `bruce init` / patched by `bruce scan` in a project's consumer role.
 */
export const ConsumerFieldUsageSchema = z.object({
  importance: CriticalitySchema,
  usedIn: z.array(z.string()),
});

export const ConsumerEndpointUsageSchema = z.object({
  method: HttpMethodSchema,
  path: z.string(),
  purpose: z.string(),
  criticality: CriticalitySchema,
  fields: z.record(z.string(), ConsumerFieldUsageSchema),
  errorHandling: z.record(z.string(), z.enum(["handled", "missing"])).optional(),
});

/**
 * Fixed vocabulary, not free text — `bruce init`/`bruce scan` ask the LLM to pick from exactly
 * this list so the dashboard can map each tag to a known icon (bruce-frontend/src/lib/techIcons.tsx)
 * without any fuzzy matching. Extend both places together when adding a new tag.
 */
export const TechStackTagSchema = z.enum([
  "nodejs",
  "typescript",
  "javascript",
  "express",
  "fastify",
  "nextjs",
  "react",
  "vue",
  "svelte",
  "python",
  "django",
  "flask",
  "fastapi",
  "go",
  "rust",
  "java",
  "spring",
  "ruby",
  "rails",
  "php",
  "laravel",
  "dotnet",
  "graphql",
  "docker",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "sqlite",
  "supabase",
]);
export type TechStackTag = z.infer<typeof TechStackTagSchema>;

export const ConsumerMappingSchema = z.object({
  producer: z.string(),
  generatedAt: z.string(),
  endpoints: z.array(ConsumerEndpointUsageSchema),
  /** 2-4 tags identifying this CONSUMER repo's own language/runtime/framework — separate from
   * whatever it's calling. Same vocabulary and icon set as producers (bruce-frontend/src/lib/techIcons.tsx). */
  techStack: z.array(TechStackTagSchema).max(4).optional(),
});
export type ConsumerMapping = z.infer<typeof ConsumerMappingSchema>;

/**
 * bruce/publisher.json
 * Generated by `bruce init` / patched by `bruce scan` in a project's publisher role.
 * This is the contract snapshot pushed via `bruce publish`.
 */
export const PublisherFieldSchema = z.object({
  type: z.string(),
  criticality: CriticalitySchema.optional(),
  /** Names of prior fields this one supersedes — lets the diff engine tell a rename/restructure from a plain removal. */
  replaces: z.array(z.string()).optional(),
});

export const PublisherEndpointSchema = z.object({
  method: HttpMethodSchema,
  path: z.string(),
  description: z.string().optional(),
  responseFields: z.record(z.string(), PublisherFieldSchema),
});

export const PublisherSnapshotSchema = z.object({
  producer: z.string(),
  generatedAt: z.string(),
  endpoints: z.array(PublisherEndpointSchema),
  /** Human-readable API docs, folded in here rather than a separate table/endpoint. */
  docsMarkdown: z.string().optional(),
  /** 2-4 tags identifying the language/runtime/framework, for the dashboard graph's tech icons. */
  techStack: z.array(TechStackTagSchema).max(4).optional(),
});
export type PublisherSnapshot = z.infer<typeof PublisherSnapshotSchema>;

export const ProducerKindSchema = z.enum(["api", "postgres"]);
export type ProducerKind = z.infer<typeof ProducerKindSchema>;

/** 'database' = auto-detected "this repo connects to its own DB producer" edge (DESIGN_NOTES.md §19). */
export const ConsumerKindSchema = z.enum(["api", "database"]);
export type ConsumerKind = z.infer<typeof ConsumerKindSchema>;

/**
 * bruce_introspect_schema() output — a full-schema snapshot pushed by a Postgres
 * event trigger (via pg_net) instead of by `bruce publish`. Unlike PublisherSnapshot,
 * this is generated by SQL introspecting information_schema, not by an LLM reading
 * source code, so there's no `criticality`/`replaces` metadata — the diff engine has
 * to infer renames/severity structurally instead (see diffDbSnapshot).
 */
export const DbColumnSchema = z.object({
  name: z.string(),
  dataType: z.string(),
  isNullable: z.boolean(),
  columnDefault: z.string().nullable(),
  isPrimaryKey: z.boolean(),
});

export const DbForeignKeySchema = z.object({
  column: z.string(),
  refSchema: z.string(),
  refTable: z.string(),
  refColumn: z.string(),
});

export const DbTableSchema = z.object({
  schema: z.string(),
  name: z.string(),
  columns: z.array(DbColumnSchema),
  primaryKey: z.array(z.string()).default([]),
  foreignKeys: z.array(DbForeignKeySchema).default([]),
});

export const DbSchemaSnapshotSchema = z.object({
  /** Optional — the DB producer's identity is established by the webhook URL/signature, not this field. */
  producer: z.string().optional(),
  generatedAt: z.string(),
  tables: z.array(DbTableSchema),
});
export type DbSchemaSnapshot = z.infer<typeof DbSchemaSnapshotSchema>;
export type DbTable = z.infer<typeof DbTableSchema>;
export type DbColumn = z.infer<typeof DbColumnSchema>;

/**
 * Change Intelligence Object — server-computed diff output, per DESIGN_NOTES.md §5.
 */
export const ApiChangeKindSchema = z.enum([
  "field_removed",
  "field_renamed",
  "field_restructured",
  "field_added",
  "endpoint_removed",
  "endpoint_added",
]);

export const DbChangeKindSchema = z.enum([
  "table_added",
  "table_dropped",
  "column_added",
  "column_dropped",
  "column_renamed",
  "column_type_changed",
  "nullability_tightened",
  "nullability_relaxed",
]);

export const ChangeKindSchema = z.enum([...ApiChangeKindSchema.options, ...DbChangeKindSchema.options]);

export const ChangeIntelligenceObjectSchema = z.object({
  type: z.enum(["breaking_change", "non_breaking_change"]),
  service: z.string(),
  endpoint: z.string(),
  change: z.object({
    kind: ChangeKindSchema,
    field: z.string(),
    replacement: z.string().optional(),
  }),
  severity: z.enum(["low", "medium", "high"]),
  affectedConsumers: z.array(z.string()),
  migration: z.object({
    required: z.boolean(),
    notes: z.string().optional(),
  }),
});
export type ChangeIntelligenceObject = z.infer<typeof ChangeIntelligenceObjectSchema>;

/**
 * JWT claim shapes for the three token kinds sharing one auth middleware
 * (owner dashboard session, producer publish key, consumer relationship key).
 */
export const OwnerSessionClaimsSchema = z.object({
  kind: z.literal("owner_session"),
  ownerId: z.string(),
  jti: z.string(),
});

export const ProducerKeyClaimsSchema = z.object({
  kind: z.literal("producer_key"),
  producerId: z.string(),
  jti: z.string(),
});

export const ConsumerKeyClaimsSchema = z.object({
  kind: z.literal("consumer_key"),
  consumerId: z.string(),
  producerId: z.string(),
  jti: z.string(),
});

/**
 * Owner-scoped, create-only credential for an AI agent to self-register new
 * producers on the owner's behalf (auto-discovery onboarding) without ever
 * handling the owner's own session token. Deliberately cannot list, read, or
 * rotate any producer/consumer key that already exists — see DESIGN_NOTES.md.
 */
export const AgentKeyClaimsSchema = z.object({
  kind: z.literal("agent_key"),
  ownerId: z.string(),
  jti: z.string(),
});

export const JwtClaimsSchema = z.discriminatedUnion("kind", [
  OwnerSessionClaimsSchema,
  ProducerKeyClaimsSchema,
  ConsumerKeyClaimsSchema,
  AgentKeyClaimsSchema,
]);
export type JwtClaims = z.infer<typeof JwtClaimsSchema>;
export type OwnerSessionClaims = z.infer<typeof OwnerSessionClaimsSchema>;
export type ProducerKeyClaims = z.infer<typeof ProducerKeyClaimsSchema>;
export type ConsumerKeyClaims = z.infer<typeof ConsumerKeyClaimsSchema>;
export type AgentKeyClaims = z.infer<typeof AgentKeyClaimsSchema>;

/**
 * bruce/consumers/index.json — manifest of registered consumer relationships.
 */
export const ConsumerRelationshipSchema = z.object({
  producerSlug: z.string(),
  producerName: z.string(),
  bruceApiUrl: z.string(),
  mappingFile: z.string(),
});

export const ConsumerIndexSchema = z.object({
  relationships: z.array(ConsumerRelationshipSchema),
});
export type ConsumerIndex = z.infer<typeof ConsumerIndexSchema>;

/**
 * .bruce/state.json — scan checkpoints, one entry per role.
 */
export const ScanStateSchema = z.object({
  lastScannedCommit: z.string().nullable(),
  lastFullScanCommit: z.string().nullable(),
  trackedFiles: z.array(z.string()),
  mappingHash: z.string().nullable(),
});
export type ScanState = z.infer<typeof ScanStateSchema>;

export const BruceStateSchema = z.object({
  producer: ScanStateSchema.optional(),
  consumers: z.record(z.string(), ScanStateSchema).optional(),
});
export type BruceState = z.infer<typeof BruceStateSchema>;
